# Generated by Django 3.2.25 on 2024-06-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_amount',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
